[input]
entrypoint = 0x80000400
# Paths are relative to the location of this config file.
elf_path = "drmario64.us.elf"
output_func_path = "funcs"

[patches]
stubs = [
]

ignored = [
]

function_sizes = [
    { name = "bcmp", size = 0x000110 },
    { name = "bcopy", size = 0x000320 },
    { name = "bzero", size = 0x0000A0 },
    { name = "sqrtf", size = 0x10 },
    { name = "guMtxCatF", size = 0x000100 },
    { name = "guMtxF2L", size = 0x000080 },
    { name = "guMtxIdent", size = 0x60 },
    { name = "guMtxIdentF", size = 0x60 },
    { name = "guMtxL2F", size = 0x80 },
    { name = "guScale", size = 0x0000c0 },
    { name = "guScaleF", size = 0x000060 },
    { name = "guTranslate", size = 0x0000E0 },
    { name = "guTranslateF", size = 0x60 },
]

hook = [
    # Load decompressed main segment
    { func = "Main_ThreadEntry", before_vram = 0x80000544, text = "load_overlays(0x011A70, (int32_t)0x80029C50, 0x899F0);" },
    # Yield infinite loop in idle thread
    { func = "Idle_ThreadEntry", before_vram = 0x800005FC, text = "yield_self_1ms(rdram);" },
]
